####################################################################################
# Title:         Cloudbox: ruTorrent | Post-Install | Settings | New Installs      #
# Author(s):     desimaniac                                                        #
# URL:           https://github.com/cloudbox/cloudbox                              #
# --                                                                               #
#         Part of the Cloudbox project: https://cloudbox.works                     #
####################################################################################
#                   GNU General Public License v3.0                                #
####################################################################################
---
- name: Post-Install | Settings | New Installs | Update 'rtorrent.rc' config settings
  ini_file:
    path: "{{ rutorrent_paths_rtorrent_rc_location }}"
    section: null
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: no
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
  loop: "{{ rutorrent_config_new_installs_rutorrent_rc_settings_list }}"

- name: Post-Install | Settings | New Installs | Enable Nginx HTTP Auth
  htpasswd:
    path: "{{ rutorrent_paths_nginx_htpasswd_location }}"
    name: "{{ user.name }}"
    password: "{{ user.pass }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775

- name: Post-Install | Settings | New Installs | Update 'php-local.ini' config settings
  ini_file:
    path: "{{ rutorrent_paths_php_local_ini_location }}"
    section: null
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: no
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
  loop: "{{ rutorrent_config_new_installs_php_local_ini_settings_list }}"

- name: Post-Install | Settings | New Installs | Import custom 'plugins.ini'
  copy:
    src: plugins.ini
    force: no
    dest: "{{ rutorrent_paths_plugins_ini_location }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
