#########################################################################
# Title:         Cloudbox: SABnzbd | Post-Install Tasks                 #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Settings Task
  import_tasks: "settings.yml"
  when: not sabnzbd_conf_stat.stat.exists
