#########################################################################
# Title:         Cloudbox: Cloudflare | Subdomains | Add Subdomain      #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Subdomains | Add Subdomain | Cloudflare: Add '{{ cloudbox_type }}' subdomain to '{{ user.domain }}'"
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    zone: "{{ user.domain }}"
    state: present
    solo: true
    proxied: no
    type: A
    value: "{{ ip_address_public }}"
    record: "{{ cloudbox_type }}"
