#########################################################################
# Title:         Cloudbox: DNS | Cloudflare | Create DNS Record         #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Cloudflare | Create DNS Record | Set 'dns_zone' variable
  set_fact:
    dns_zone: "{{ dns_zone | default(user.domain) }}"

- name: Cloudflare | Create DNS Record | Set DNS Record
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    zone: "{{ dns_zone }}"
    state: present
    solo: true
    proxied: no
    type: A
    value: "{{ ip_address_public }}"
    record: "{{ dns_record }}"
  register: cloudflare_dns_record_creation_status

- name: Cloudflare | Create DNS Record | Tasks on success
  block:

  - name: Cloudflare | Create DNS Record | Set 'dns_record_print' variable
    set_fact:
      dns_record_print: "{{ (dns_record == dns_zone) | ternary(dns_zone,dns_record + '.' + dns_zone) }}"

  - name: Cloudflare | Create DNS Record | Display DNS Record creation status
    debug:
      msg: "DNS Record for '{{ dns_record_print }}' set to '{{ ip_address_public }}'."

  when: cloudflare_dns_record_creation_status is succeeded
